
  CREATE TABLE "MUSEUM00"."GNM_MAIN" 
   (	"IDENT" NUMBER(10,0), 
	"INVNR" VARCHAR2(200 BYTE), 
	"TITEL" VARCHAR2(1000 BYTE), 
	"INVNRALT" VARCHAR2(500 BYTE), 
	"TECHNIK" VARCHAR2(500 BYTE), 
	"MATERIAL" VARCHAR2(200 BYTE), 
	"DATIERUNG" VARCHAR2(150 BYTE), 
	"DATIERUNG_VORL" VARCHAR2(150 BYTE), 
	"SCHUCHARDTBANDN" NUMBER(5,0), 
	"SCHUCHARDTSEITEN" NUMBER(5,0), 
	"SCHUCHARDTNRN" NUMBER(5,0), 
	"SCHUCHARDTKVN" NUMBER(5,0), 
	"SCHUCHARDTZUSATZN" VARCHAR2(5 BYTE), 
	"INVNR_GATTUNG" VARCHAR2(6 BYTE), 
	"INVNR_JAHRESZAHL" NUMBER(4,0), 
	"INVNR_LFDNR" NUMBER(6,0), 
	"INVNR_SUFFIX" NUMBER(4,0), 
	"GATTUNG" VARCHAR2(50 BYTE), 
	"GATTUNG_SACHBEGRIFF" VARCHAR2(60 BYTE), 
	"SAMMLUNGSBEREICH" VARCHAR2(100 BYTE), 
	"INVNR_LEIHGABE" VARCHAR2(4 BYTE), 
	"FIRST_USER_NAME" VARCHAR2(50 BYTE), 
	"FIRST_USER_DATE" DATE, 
	"LAST_USER_NAME" VARCHAR2(50 BYTE), 
	"LAST_USER_DATE" DATE, 
	"JOURNALDRUCK" VARCHAR2(1 BYTE), 
	"OEFFENTLICH" VARCHAR2(1 BYTE), 
	"SIGNATUR_UND_DATUM" VARCHAR2(250 BYTE), 
	"FREIGABE_INTERNET" VARCHAR2(4 BYTE), 
	"BESTANDSBEREICH_IDENT" NUMBER(12,0), 
	"BESTANDSBEREICH_NAME" VARCHAR2(150 BYTE), 
	"BEMERKUNGEN" VARCHAR2(4000 BYTE), 
	"BESCHRIFTUNG" VARCHAR2(4000 BYTE), 
	"VERBALE_BESCHREIBUNG" VARCHAR2(4000 BYTE), 
	"ERHALTUNGSZUSTAND" VARCHAR2(2500 BYTE), 
	"ZEUGNISSE" VARCHAR2(2000 BYTE), 
	"DATENSATZSTATUS" NUMBER(5,0), 
	"GATTUNG_IDENT" NUMBER(5,0), 
	"PERSONEN_GESAMT" VARCHAR2(4000 BYTE) GENERATED ALWAYS AS ("MUSEUM00"."GET_PERSONEN_GESAMT"("IDENT")) VIRTUAL , 
	"TITEL_PUBLIC" VARCHAR2(1000 BYTE), 
	"DATENSATZ_VERANTWORTLICH" VARCHAR2(200 BYTE), 
	"TEILE" NUMBER(4,0) DEFAULT 1, 
	"OBJEKTTYP_IDENT" NUMBER, 
	"KATEGORIE_IDENT" NUMBER, 
	"WISS_BEZEICHNUNG" VARCHAR2(250 BYTE), 
	"SND_NR" VARCHAR2(20 BYTE), 
	"GND_ID" VARCHAR2(20 BYTE), 
	"STRUNZ" VARCHAR2(100 BYTE), 
	"HOELZEL" VARCHAR2(100 BYTE), 
	"DELETED" NUMBER(1,0), 
	"SCHUCHARDT" VARCHAR2(100 BYTE), 
	"EFRE" NUMBER(1,0), 
	"BIOZIDBELASTUNG" NUMBER(*,0), 
	"SAMMLUNGSBEREICH_IDENT" NUMBER, 
	"TITEL_UNICODE" NVARCHAR2(1000), 
	"STICHWORTE" VARCHAR2(2000 BYTE), 
	"ONLINESAMMLUNG" NUMBER(1,0), 
	"ONLINESAMMLUNG_EXPORT" NUMBER(1,0), 
	"ATMOSPHAEREKAMMER_DATUM" DATE, 
	"BERGUNGSPRIORITAT_IDENT" NUMBER, 
	"CREATE_USER" VARCHAR2(80 BYTE), 
	"CREATE_DATE" DATE, 
	"EDIT_USER" VARCHAR2(80 BYTE), 
	"EDIT_DATE" DATE, 
	"DATIERUNG_HISTORIE" VARCHAR2(150 BYTE), 
	"DELETED_BY" VARCHAR2(80 BYTE), 
	"DELETED_DATE" DATE, 
	"PRAESENTATIONSTITEL_IDENT" NUMBER, 
	"DATIERUNG_PREMIGRATION" VARCHAR2(150 BYTE), 
	"MATERIAL_TECHNIK_EXTERN" VARCHAR2(2000 BYTE), 
	"CREDITLINE" VARCHAR2(500 BYTE), 
	"ERWERBER_IDENT" NUMBER, 
	"MATERIAL_TECHNIK" VARCHAR2(4000 BYTE), 
	"SIGNATUR_UND_DATUM_PM" VARCHAR2(250 BYTE), 
	"RECHTEINHABER" VARCHAR2(250 BYTE), 
	"URHEBER" VARCHAR2(250 BYTE), 
	"NUTZUNGSAUFLAGEN" VARCHAR2(2000 BYTE), 
	"OA_GRUND" NUMBER, 
	"OA_DATUM" DATE, 
	"OA_BEMERKUNGEN" VARCHAR2(1000 BYTE), 
	"EXP_STATUS_DIGITALISATE" NUMBER(1,0), 
	"EXP_STATUS_KUSTODIE" NUMBER(1,0), 
	"EXP_STATUS_RESTAURIERUNG" NUMBER(1,0), 
	"TEILBEREICHE" VARCHAR2(4000 BYTE), 
	"MATERIAL_TECHNIK_L" NUMBER(1,0), 
	"MATERIAL_TECHNIK_EXTERN_L" NUMBER(1,0), 
	"PERSONEN_GESAMT_SUCHE" VARCHAR2(4000 BYTE), 
	"EFRE_DIGIPROJEKT" NUMBER(1,0), 
	"BMBF_PROJEKT" NUMBER(1,0), 
	"UTF8_TEST" NVARCHAR2(20), 
	"VOLLTEXT" CHAR(1 BYTE), 
	 CONSTRAINT "PK_GNM_MAIN" PRIMARY KEY ("IDENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."IDENT" IS 'PK';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."INVNR" IS 'Inventarnummer';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."TITEL" IS 'Gegenstand';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."INVNRALT" IS 'alte Inventarnummer';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."INVNR_GATTUNG" IS 'Gattungskürzel';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."INVNR_LFDNR" IS 'Konvolut-LfdNr
';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."TITEL_PUBLIC" IS 'Präsentationstitel';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."TEILE" IS 'neue MDB-Version';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."OBJEKTTYP_IDENT" IS 'neue MDB-Vers';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."KATEGORIE_IDENT" IS 'neue MDB-Vers';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."WISS_BEZEICHNUNG" IS 'neue MDB-Vers';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."SND_NR" IS 'neue MDB-Vers';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."GND_ID" IS 'neue MDB-Vers';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."STRUNZ" IS 'neue MDB-Vers';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."HOELZEL" IS 'neue MDB-Vers';
   COMMENT ON COLUMN "MUSEUM00"."GNM_MAIN"."PRAESENTATIONSTITEL_IDENT" IS 'Präsentationstitel Referenz';

  CREATE INDEX "MUSEUM00"."GNM_MAIN_INDEX1" ON "MUSEUM00"."GNM_MAIN" (LOWER("MATERIAL_TECHNIK")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."GNM_MAIN_INDEX2" ON "MUSEUM00"."GNM_MAIN" (LOWER("MATERIAL_TECHNIK_EXTERN")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."GNM_MAIN_INDEX3" ON "MUSEUM00"."GNM_MAIN" (LOWER("INVNRALT")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."GNM_MAIN_INDEX4" ON "MUSEUM00"."GNM_MAIN" (LOWER("VERBALE_BESCHREIBUNG")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."GNM_MAIN_INDEX5" ON "MUSEUM00"."GNM_MAIN" (LOWER("BEMERKUNGEN")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."GNM_MAIN_INVNR_LOWER" ON "MUSEUM00"."GNM_MAIN" (LOWER("INVNR")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."IDX_BESTANDSBEREICH_IDENT" ON "MUSEUM00"."GNM_MAIN" ("BESTANDSBEREICH_IDENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."IDX_LASTUSERDATE" ON "MUSEUM00"."GNM_MAIN" ("LAST_USER_DATE" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."IDX_TITELPUBLIC" ON "MUSEUM00"."GNM_MAIN" ("TITEL_PUBLIC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MUSEUM_DATA" ;

  CREATE INDEX "MUSEUM00"."OBJEKTSUCHE_FTX" ON "MUSEUM00"."GNM_MAIN" ("VOLLTEXT") 
   INDEXTYPE IS "CTXSYS"."CONTEXT" ;

  CREATE INDEX "MUSEUM00"."OBJEKTSUCHE_NEU_FTX" ON "MUSEUM00"."GNM_MAIN" ("TITEL") 
   INDEXTYPE IS "CTXSYS"."CONTEXT"  PARAMETERS ('
  datastore      objekte_neu_ds
  section group  objekte_neu_sg
  wordlist       objekte_wl
  lexer          objekte_lx
  stoplist       ctxsys.empty_stoplist
  memory 500M
');

  CREATE OR REPLACE EDITIONABLE TRIGGER "MUSEUM00"."T_DEL_GNM_MAIN" 
BEFORE DELETE ON GNM_MAIN 
FOR EACH ROW
DECLARE 
Current_User varchar2(50);   
BEGIN
  SELECT sys_context('USERENV', 'SESSION_USER') INTO Current_User FROM dual;
  INSERT INTO GNM_MAIN_LOG 
  VALUES
  (:OLD.IDENT, :OLD.INVNR, :OLD.TITEL, :OLD.INVNRALT, :OLD.TECHNIK, :OLD.MATERIAL, :OLD.DATIERUNG, :OLD.DATIERUNG_VORL, 
  :OLD.SCHUCHARDTBANDN, :OLD.SCHUCHARDTSEITEN, :OLD.SCHUCHARDTNRN, :OLD.SCHUCHARDTKVN, :OLD.SCHUCHARDTZUSATZN, 
  :OLD.INVNR_GATTUNG, :OLD.INVNR_JAHRESZAHL, :OLD.INVNR_LFDNR, :OLD.INVNR_SUFFIX, :OLD.GATTUNG, :OLD.GATTUNG_SACHBEGRIFF, 
  :OLD.SAMMLUNGSBEREICH, :OLD.INVNR_LEIHGABE, :OLD.FIRST_USER_NAME, :OLD.FIRST_USER_DATE, :OLD.LAST_USER_NAME, 
  :OLD.LAST_USER_DATE, :OLD.JOURNALDRUCK, :OLD.OEFFENTLICH, :OLD.SIGNATUR_UND_DATUM, :OLD.FREIGABE_INTERNET, 
  :OLD.BESTANDSBEREICH_IDENT, :OLD.BESTANDSBEREICH_NAME, :OLD.BEMERKUNGEN, :OLD.BESCHRIFTUNG, :OLD.VERBALE_BESCHREIBUNG, 
  :OLD.ERHALTUNGSZUSTAND, :OLD.ZEUGNISSE, :OLD.DATENSATZSTATUS, :OLD.GATTUNG_IDENT, :OLD.TITEL_PUBLIC, 
  :OLD.DATENSATZ_VERANTWORTLICH, :OLD.TEILE, :OLD.OBJEKTTYP_IDENT, :OLD.KATEGORIE_IDENT, :OLD.WISS_BEZEICHNUNG, 
  :OLD.SND_NR, :OLD.GND_ID, :OLD.STRUNZ, :OLD.HOELZEL, :OLD.DELETED, :OLD.SCHUCHARDT, :OLD.EFRE, 
  'deleted', CURRENT_USER, SYSDATE);  
END;
/
ALTER TRIGGER "MUSEUM00"."T_DEL_GNM_MAIN" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MUSEUM00"."T_IUB_VOLLTEXTSUCHE" 
  AFTER INSERT OR UPDATE OR DELETE ON GNM_MAIN 
  FOR EACH ROW
DECLARE
  vSUCHTEXT CLOB;
  vINVNR_GESAMT VARCHAR2(2000);
  vExists number;
BEGIN

IF DELETING THEN 
  DELETE FROM VOLLTEXTSUCHE WHERE IDENT = :old.IDENT;
END IF;

IF INSERTING THEN
  IF :NEW.INVNR_SUFFIX IS NULL THEN
    vINVNR_GESAMT := :NEW.INVNR;
  ELSE  
    vINVNR_GESAMT := :NEW.INVNR || '.' || :NEW.INVNR_SUFFIX;
  END IF;  

  vSUCHTEXT := TO_CHAR(:NEW.IDENT) || ' # ' || vINVNR_GESAMT || ' # ' || :NEW.INVNRALT || ' # ' || :NEW.DATIERUNG || ' # ' ||
    :NEW.DATIERUNG_VORL || ' # ' || :NEW.GATTUNG || ' # ' || :NEW.GATTUNG_SACHBEGRIFF || ' # ' || :NEW.SAMMLUNGSBEREICH || ' # ' ||
    :NEW.SIGNATUR_UND_DATUM || ' # ' || :NEW.PERSONEN_GESAMT || ' # ' || :NEW.TITEL || ' # ' || :NEW.TITEL_PUBLIC || ' # ' || 
    :NEW.BEMERKUNGEN || ' # ' || :NEW.BESCHRIFTUNG || ' # ' || :NEW.VERBALE_BESCHREIBUNG || ' # ' || :NEW.ZEUGNISSE || ' # ' || 
    :NEW.TECHNIK || ' # ' || :NEW.MATERIAL || ' # ' || :NEW.ERHALTUNGSZUSTAND;

  INSERT INTO VOLLTEXTSUCHE VALUES (:NEW.IDENT, vSUCHTEXT);
END IF;

IF UPDATING THEN
  IF :NEW.INVNR_SUFFIX IS NULL THEN
    vINVNR_GESAMT := :NEW.INVNR;
  ELSE  
    vINVNR_GESAMT := :NEW.INVNR || '.' || :NEW.INVNR_SUFFIX;
  END IF;

  vSUCHTEXT := TO_CHAR(:NEW.IDENT) || ' # ' || vINVNR_GESAMT || ' # ' || :NEW.INVNRALT || ' # ' || :NEW.DATIERUNG || ' # ' ||
    :NEW.DATIERUNG_VORL || ' # ' || :NEW.GATTUNG || ' # ' || :NEW.GATTUNG_SACHBEGRIFF || ' # ' || :NEW.SAMMLUNGSBEREICH || ' # ' ||
    :NEW.SIGNATUR_UND_DATUM || ' # ' || :NEW.PERSONEN_GESAMT || ' # ' || :NEW.TITEL || ' # ' || :NEW.TITEL_PUBLIC || ' # ' || 
    :NEW.BEMERKUNGEN || ' # ' || :NEW.BESCHRIFTUNG || ' # ' || :NEW.VERBALE_BESCHREIBUNG || ' # ' || :NEW.ZEUGNISSE || ' # ' || 
    :NEW.TECHNIK || ' # ' || :NEW.MATERIAL || ' # ' || :NEW.ERHALTUNGSZUSTAND;

  SELECT COUNT(IDENT) INTO vEXISTS FROM VOLLTEXTSUCHE WHERE IDENT = :NEW.IDENT;

  IF vEXISTS > 0 THEN  
    UPDATE VOLLTEXTSUCHE SET TEXT = vSUCHTEXT WHERE IDENT = :NEW.IDENT;
  ELSE
    INSERT INTO VOLLTEXTSUCHE VALUES (:NEW.IDENT, vSUCHTEXT);
  END IF;
END IF;     

END;
/
ALTER TRIGGER "MUSEUM00"."T_IUB_VOLLTEXTSUCHE" DISABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MUSEUM00"."T_IB_GNM_MAIN" 
BEFORE INSERT ON "MUSEUM00"."GNM_MAIN" FOR EACH ROW
DECLARE 
Current_User varchar2(50);
BEGIN
  SELECT sys_context('USERENV', 'SESSION_USER') INTO Current_User FROM dual;
  :NEW.CREATE_USER := CURRENT_USER;
  :NEW.CREATE_DATE := SYSDATE;
  :NEW.EDIT_USER := CURRENT_USER;
  :NEW.EDIT_DATE := SYSDATE;
END;
/
ALTER TRIGGER "MUSEUM00"."T_IB_GNM_MAIN" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MUSEUM00"."T_UB_GNM_MAIN" 
BEFORE UPDATE ON "MUSEUM00"."GNM_MAIN" FOR EACH ROW
DECLARE 
Current_User varchar2(50);
BEGIN
  SELECT sys_context('USERENV', 'SESSION_USER') INTO Current_User FROM dual;
  :NEW.EDIT_USER := CURRENT_USER;
  :NEW.EDIT_DATE := SYSDATE;
END;
/
ALTER TRIGGER "MUSEUM00"."T_UB_GNM_MAIN" ENABLE;


  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "FOTOTHEK00" WITH GRANT OPTION;
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "FOTOTHEK_ONLINE_READ";
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "WEBDBSYNC";
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "AUSSTELLUNGEN00" WITH GRANT OPTION;
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "AUSSTELLUNGEN_READ";
  GRANT UPDATE ON "MUSEUM00"."GNM_MAIN" TO "MUSEUM_WRITE";
  GRANT INSERT ON "MUSEUM00"."GNM_MAIN" TO "MUSEUM_WRITE";
  GRANT DELETE ON "MUSEUM00"."GNM_MAIN" TO "MUSEUM_WRITE";
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "FOTOWARE00" WITH GRANT OPTION;
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "MUSEUM_READ";
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "S_PND_LINKINFO";
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "DIGIVERWALTUNG00" WITH GRANT OPTION;
  GRANT SELECT ON "MUSEUM00"."GNM_MAIN" TO "PNDSWK00" WITH GRANT OPTION;
